name: cctv_streaming
description: "RTSP CCTV Streaming Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.0
  
  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Video Player
  video_player: ^2.8.2
  chewie: ^1.7.5
  
  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  
  # Utils
  url_launcher: ^6.2.4
  flex_color_picker: ^3.8.0
  
  # Platform-specific (Android/iOS)
  webview_flutter: ^4.10.0
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
